name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "head"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        rubygems: latest

    - name: Install Ruby dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run tests
      run: bundle exec rake test

    - name: Install Node dependencies
      run: |
        npm install -g yarn
        yarn install --frozen-lockfile

    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps

    - name: Run e2e tests
      run: yarn test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Run linter
      run: bundle exec rake standard
